set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_1_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_1_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_sck_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_ss1_o]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_ss2_o]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_0_ss_io]
set_property IOSTANDARD LVCMOS33 [get_ports UART_0_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_0_0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_p_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_n_0]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_1[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_1[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_p_1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_n_1]
set_property IOSTANDARD LVCMOS33 [get_ports buzz_out_0]


set_property PACKAGE_PIN C20 [get_ports {DAC_out_0[0]}]
set_property PACKAGE_PIN B20 [get_ports {DAC_out_0[1]}]
set_property PACKAGE_PIN A20 [get_ports {DAC_out_0[2]}]
set_property PACKAGE_PIN B19 [get_ports {DAC_out_0[3]}]
set_property PACKAGE_PIN D18 [get_ports {DAC_out_0[4]}]
set_property PACKAGE_PIN E17 [get_ports {DAC_out_0[5]}]
set_property PACKAGE_PIN G15 [get_ports {DAC_out_0[6]}]
set_property PACKAGE_PIN G14 [get_ports {DAC_out_0[7]}]
set_property PACKAGE_PIN F16 [get_ports {DAC_out_0[8]}]
set_property PACKAGE_PIN F17 [get_ports {DAC_out_0[9]}]
set_property PACKAGE_PIN E18 [get_ports {DAC_out_0[10]}]
set_property PACKAGE_PIN E19 [get_ports {DAC_out_0[11]}]
set_property PACKAGE_PIN F19 [get_ports {DAC_out_0[12]}]
set_property PACKAGE_PIN F20 [get_ports {DAC_out_0[13]}]
set_property PACKAGE_PIN D19 [get_ports clk_p_0]
set_property PACKAGE_PIN D20 [get_ports clk_n_0]
set_property PACKAGE_PIN U18 [get_ports {DAC_out_1[0]}]
set_property PACKAGE_PIN V18 [get_ports {DAC_out_1[1]}]
set_property PACKAGE_PIN W16 [get_ports {DAC_out_1[2]}]
set_property PACKAGE_PIN W15 [get_ports {DAC_out_1[3]}]
set_property PACKAGE_PIN V15 [get_ports {DAC_out_1[4]}]
set_property PACKAGE_PIN W14 [get_ports {DAC_out_1[5]}]
set_property PACKAGE_PIN Y14 [get_ports {DAC_out_1[6]}]
set_property PACKAGE_PIN Y16 [get_ports {DAC_out_1[7]}]
set_property PACKAGE_PIN Y17 [get_ports {DAC_out_1[8]}]
set_property PACKAGE_PIN W18 [get_ports {DAC_out_1[9]}]
set_property PACKAGE_PIN Y18 [get_ports {DAC_out_1[10]}]
set_property PACKAGE_PIN W19 [get_ports {DAC_out_1[11]}]
set_property PACKAGE_PIN Y19 [get_ports {DAC_out_1[12]}]
set_property PACKAGE_PIN W20 [get_ports {DAC_out_1[13]}]
set_property PACKAGE_PIN U19 [get_ports clk_p_1]
set_property PACKAGE_PIN V20 [get_ports clk_n_1]
set_property PACKAGE_PIN T10 [get_ports UART_0_0_txd]
set_property PACKAGE_PIN T11 [get_ports UART_0_0_rxd]
set_property PACKAGE_PIN M20 [get_ports SPI_0_0_sck_io]
set_property PACKAGE_PIN M19 [get_ports SPI_0_0_io0_io]
set_property PACKAGE_PIN T14 [get_ports SPI_0_0_ss_io] 
set_property PACKAGE_PIN T15 [get_ports SPI_0_0_io1_io] 
set_property PACKAGE_PIN P14 [get_ports SPI_0_0_ss2_o]
set_property PACKAGE_PIN R14 [get_ports SPI_0_0_ss1_o] 
set_property PACKAGE_PIN K19 [get_ports IIC_0_0_sda_io]
set_property PACKAGE_PIN L20 [get_ports IIC_0_0_scl_io]
set_property PACKAGE_PIN U14 [get_ports IIC_1_0_scl_io]
set_property PACKAGE_PIN W13 [get_ports IIC_1_0_sda_io]
set_property PACKAGE_PIN P19 [get_ports {gpio_io_o_0[0]}] 
set_property PACKAGE_PIN N20 [get_ports {gpio_io_o_0[1]}]
set_property PACKAGE_PIN P20 [get_ports {gpio_io_o_0[2]}]
set_property PACKAGE_PIN G20 [get_ports {gpio_io_o_0[3]}] 
set_property PACKAGE_PIN U20 [get_ports {gpio_io_o_0[4]}] 
set_property PACKAGE_PIN J19 [get_ports {gpio_io_o_0[5]}] 
set_property PACKAGE_PIN G18 [get_ports {gpio_io_o_0[6]}] 
set_property PACKAGE_PIN J20 [get_ports {gpio_io_o_0[7]}] 
set_property PACKAGE_PIN H20 [get_ports {gpio_io_o_0[8]}]
set_property PACKAGE_PIN G19 [get_ports {gpio_io_o_0[9]}] 
set_property PACKAGE_PIN J16 [get_ports {gpio_io_o_0[10]}] 
set_property PACKAGE_PIN J14 [get_ports {gpio_io_o_0[11]}] 
set_property PACKAGE_PIN L19 [get_ports {gpio_io_o_0[12]}] 
set_property PACKAGE_PIN L17 [get_ports {gpio_io_o_0[13]}] 
set_property PACKAGE_PIN K17 [get_ports {gpio_io_o_0[14]}] 
set_property PACKAGE_PIN K18 [get_ports {gpio_io_o_0[15]}] 
set_property PACKAGE_PIN H15 [get_ports buzz_out_0] 

set_property PULLTYPE PULLUP [get_ports IIC_1_0_scl_io]
set_property PULLTYPE PULLUP [get_ports IIC_1_0_sda_io]
set_property PULLTYPE PULLUP [get_ports IIC_0_0_scl_io]
set_property PULLTYPE PULLUP [get_ports IIC_0_0_sda_io]

#set_property PACKAGE_PIN P19 [get_ports {GPIO_0_tri_io[0]}] LCD_RST
#set_property PACKAGE_PIN N20 [get_ports {GPIO_0_tri_io[1]}] LCD_DC
#set_property PACKAGE_PIN P20 [get_ports {GPIO_0_tri_io[2]}] LCD_CS
#set_property PACKAGE_PIN G20 [get_ports {GPIO_0_tri_io[3]}] K0
#set_property PACKAGE_PIN U20 [get_ports {GPIO_0_tri_io[4]}] K1
#set_property PACKAGE_PIN J19 [get_ports {GPIO_0_tri_io[5]}] DIN
#set_property PACKAGE_PIN G18 [get_ports {GPIO_0_tri_io[6]}] LDAC
#set_property PACKAGE_PIN J20 [get_ports {GPIO_0_tri_io[7]}] CLR
#set_property PACKAGE_PIN H20 [get_ports {GPIO_0_tri_io[8]}] SCLK
#set_property PACKAGE_PIN G19 [get_ports {GPIO_0_tri_io[9]}] SYNC
#set_property PACKAGE_PIN H15 [get_ports {GPIO_0_tri_io[10]}] BUZZ
#set_property PACKAGE_PIN J14 [get_ports {GPIO_0_tri_io[11]}] TF_CD
#set_property PACKAGE_PIN L19 [get_ports {GPIO_0_tri_io[12]}] TF_CD
